### ISSUE TITLE
Publishing to hex

### ISSUE THREAD

**Issue by starbelly** [kafka4beam/sasl_auth#15]
We have a few odds and ends we want to do to do including #9, and a few issues I'm about to open. That said, I'm not sure I see a reason to wait publishing this to hex. We could publish it as an RC or pre. 

To note, I thought sasl_auth was already on hex, it is not, nor is brod_gsspai.

**Comment by kjellwinblad** [comment]
I also think we can publish it on hex (to make it easier for people to use), but I have never published anything on hex before, so I don't know the requirements. Feel free to go ahead and publish it and let me know if you need help from me or EMQX.

**Comment by starbelly** [comment]
I'll go ahead and publish a pre-release. I'll add you, Stone, and Vikas as owners. When you like I can walk you through this if desired.

**Comment by starbelly** [comment]
@kjellwinblad  What is your username on hex? Feel free to DM me that. 

For @zmstone and @vikas15bhardwaj  you were added as owners. 

https://hex.pm/packages/sasl_auth 

https://hexdocs.pm/sasl_auth/readme.html

**Comment by kjellwinblad** [comment]
I did not have any account before but I have one now :smile: 

Here is my username: kjellwinblad

**Comment by starbelly** [comment]
> kjellwinblad

Added :)
