### ISSUE TITLE
Cleanup Makefile for macos 

### ISSUE THREAD

**Issue by starbelly** [kafka4beam/sasl_auth#16]
The Makefile is a bit clumsy in regards to mac os. Specifically, we're assuming everyone has cyrus-sasl and krb5 installed via brew. We should probably check if brew is installed, then check if cyrus-sasl is installed via brew. If brew is not installed or cyrus-sasl is not installed via brew, don't append include and lib paths to flags.

**Comment by kjellwinblad** [comment]
I think the situation is similar on other OSes as well. We assume that the dependencies are installed, and if something is missing, the build or the test (as there is a dynamic library dependency that will not break the build) will break. I added a little more documentation to the README file about dependencies in PR https://github.com/kafka4beam/sasl_auth/pull/18. I think we can "solve" this by adding a short description about what needs to be installed on Mac OS to the README after PR https://github.com/kafka4beam/sasl_auth/pull/18 is merged. @starbelly what do you think?

**Comment by starbelly** [comment]
@kjellwinblad I agree.

**Comment by kjellwinblad** [comment]
@starbelly can you create a PR that updates the Dependencies section in the README.md file with a description about what is needed for MacOS? I do not have a MacOS computer so I think it might be easier for you to do that.
