### ISSUE TITLE
Add sasl and enif mutexes

### ISSUE THREAD

**Issue by starbelly** [kafka4beam/sasl_auth#27]
Per the cyrus-sasl documentation, in order to have some assurance of thread safety, sasl mutex callbacks must be provided. In addition, we should also wrap sasl calls in an enif mutex to be on the safe side.

**Comment by starbelly** [comment]
@kjellwinblad I've noticed sporadic segfaults. Unfortunately, I am not able to reproduce this. The general area where a segfault happens is known though, and is [here](https://github.com/cyrusimap/cyrus-sasl/blob/7e2feaeeb2e37d38cb5fa957d0e8a599ced22612/plugins/gssapi.c#L2323). 

I can only presume that that this is because of mutexes not being provided, though I can thing of some other exotic possibilities.

**Comment by starbelly** [comment]
Small update, while we absolutely should be using cyrus-sasl mutex callbacks (and using mutex as additional guards around cyrus-sasl calls), this is not the issue I ran into. It is still a bit elusive, however I upon re-visiting the code I found a few issues, one of which we knew about already : 

1. The one issue that was known is that sharing a sasl context across a process can (and will) result in a segfault, while this the library is not intended to be used this way, we should guard against it. The main guard in a patch I will send up is what zlib in otp does, specifically it checks that calling process is the same as the calling process that created the resource originally. In addition, mutexes will be added around cyrus-sasl calls (though that's mainly to guard against problems with a small bit of global state in cyrus-sasl). 

2. We are copying the principal pointer to the callback structure, since the principal is usually going to be < 32 bytes, it could dissapear on us, this would definitely cause an issue if cyrus-sasl tries to access the user name/id on the context. Going forward (with a patch I'm working on and testing) we'll simply copy arguments into unsigned char pointers and pass those and free when appropriate. 

3. In running the nif in the erlang debug emulator, it was observed that cyrus-sasl may mutate a challenge binary we pass on to it in mech step. If this is so, it could corrupt the heap, and result in undefined behaviour, I do believe. So, we'll just copy it into an unsigned char pointer and pass that in, freeing after the call.

**Comment by kjellwinblad** [comment]
Hi @starbelly, Thanks for finding all these problems and that you are working on fixes. As far as I know we have not heard of problems with crashes but this does not mean they have not happened. Let me know when you have a PR ready and I will review it.

**Comment by starbelly** [comment]
> Hi @starbelly, Thanks for finding all these problems and that you are working on fixes. As far as I know we have not heard of problems with crashes but this does not mean they have not happened. Let me know when you have a PR ready and I will review it.

I will get a PR in a minute. We'll have to go over what we think is needed and what is pure defensiveness and what we see as not helping anything, I chose pure defensiveness in battling this one, since making a reproducer is extremely difficult, though I'm still looking into that using `rr`.
